name: CI Workflow

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Repository Download
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.7"

      - name: Install Chrome
        id: setup-chrome
        uses: browser-actions/setup-chrome@v2
        with:
          install-chromedriver: true
          install-dependencies: true

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Install project dependencies with poetry
        run: poetry install --no-interaction

      - name: Run Tests
        env:
          CHROME_BIN: ${{ steps.setup-chrome.outputs.chrome-path }}
          CHROMEDRIVER: ${{ steps.setup-chrome.outputs.chromedriver-path }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        run: poetry run pytest
