name: CI Workflow

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Repository Download
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.7"

      - name: Install Firefox
        uses: browser-actions/setup-firefox@v1

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Install project dependencies with poetry
        run: poetry install --no-interaction

      - name: Run Tests
        run: poetry run pytest
