name: CI Workflow

on: pull_request
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Repository Download
              uses: actions/checkout@v4

            - name: Install Python
              uses: actions/setup-python@v5
              with:
                python-version: 3.12.7

            - name: Install Poetry
              run: |
                curl -sSL https://install.python-poetry.org | python3 -

            - name: Install project dependencies with poetry
              run: poetry install

            - name: Run Tests
              run: poetry run pytest
